version: '3.8'
services:
  ord:
    container_name: ord
    build:
      context: .
    command:  ["--data-dir", "/index-data", "--rpc-url", "s444jy4lmzwf6mtix776q35k6njhpminkswrndifnm27bvv2tqkclwad.onion:8332", "server", "--http-port", "8080"]
    volumes:
      - index_data:/index-data
    environment:
      - ORD_BITCOIN_RPC_USER=$RPC_USER
      - ORD_BITCOIN_RPC_PASS=$RPC_PASSWORD
    ports:
      - "8080:8080"

volumes:
  index_data:
