version: '3.8'
services:
  ord:
    container_name: ord
    build:
      context: .
    command:  ["--data-dir", "/index-data", "--rpc-url", "vmmvtnropan2pydqw6bezvbjvhd7iebwsjzpegb3x7bmah6kez7vmxyd.onion", "server"]
    volumes:
      - index_data:/index-data
    environment:
      - ORD_BITCOIN_RPC_USER=$RPC_USER
      - ORD_BITCOIN_RPC_PASS=$RPC_PASSWORD
    ports:
      - "8080:8080"

volumes:
  index_data:

